### ISSUE TITLE
[PE-D][Tester C] Strange cap on number of exercises that can be generated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-2/tp#148]
"generate 873" works just fine but if the number is >= 874, excluding 1337, app cannot generate exercises

![image.png](https://raw.githubusercontent.com/YatPang/ped/main/files/054fc1f9-35a3-489d-a68c-1d1e363010d5.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: YatPang/ped#4

**Comment by EangJS** [comment]
Not a bug. 
Should write in UG the cap of exercises.

**Comment by Khulon** [comment]
will add exception and update ug

**Comment by Khulon** [comment]
doned
