### ISSUE TITLE
[PE-D][Tester C] "quick" command with inputs 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-2/tp#156]
When "quick" command has inputs, it does not work.

![image.png](https://raw.githubusercontent.com/YatPang/ped/main/files/9ec91ace-de0f-4590-a187-5e5897b0b78e.png)

![image.png](https://raw.githubusercontent.com/YatPang/ped/main/files/8c4a8168-fab1-4132-bad6-fe58508f4b40.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: YatPang/ped#6

**Comment by Khulon** [comment]
fixed
