### ISSUE TITLE
[PE-D][Tester C] "quick" command malfunctioning

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-2/tp#159]
home_leg_day exercise is not in the workout plan, yet when "quick home_leg_day 3" is called, the exercise was found, before a conflicting output stating "no such plan"

![image.png](https://raw.githubusercontent.com/YatPang/ped/main/files/a15d134f-500f-4421-b404-5bdc83b67801.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: YatPang/ped#7

**Comment by Khulon** [comment]
fixed
