### ISSUE TITLE
[PE-D][Tester E] File Storage system may have issues

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-2/tp#165]
I found the following in a file termed fitness_duke.log

```
Mar 31, 2023 4:46:10 PM seedu.duke.storage.JsonUserCareerStorage loadUserData
WARNING: Data file has been corrupted or missing, we will create a new file and reset your progress.
Mar 31, 2023 4:46:10 PM seedu.duke.storage.JsonUserPlansStorage loadUserPlans
WARNING: Plans data file has been corrupted or missing, we will create a new file for you, all your plans will be lost.

```

I had opened this file on 31st March at 5 30 or so, well after 4:46 pm, there seem to be some unresolved issues with respect to saving and loading data.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: lihka1202/ped#9

**Comment by EangJS** [comment]
This is just our logger message which is just a warning to the user that we could not find any data file / data file is corrupted. 
This is not a bug.
