### ISSUE TITLE
[PE-D][Tester C] "delete" working outside of planner mode

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W13-2/tp#169]
"delete" is listed as a command available in planner mode and not outside of planner mode, but usable outside of planner mode

![image.png](https://raw.githubusercontent.com/YatPang/ped/main/files/177ae2c3-4099-4800-a0c2-6ea15df2cd1f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YatPang/ped#11

**Comment by EangJS** [comment]
The delete command is available in both main menu and workout mode.
Both performs two **very** different functionalities as stated in UG.

* One for deleting workout sessions
* The other for deleting plans
