### ISSUE TITLE
[PE-D][Tester A] quick command does not recognize plans with duplicate names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W13-2/tp#172]
upon creating two workout plans with identical names but different filters, the quick command only generates workouts based on the filter of the first plan

![image.png](https://raw.githubusercontent.com/Jjzeng123/ped/main/files/f819149f-8050-4f9d-8b48-5e8228c757b0.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Jjzeng123/ped#7

**Comment by Khulon** [comment]
fixed by not allowing duplicate names
