### ISSUE TITLE
Save exercises by history and date

### ISSUE THREAD

**Issue by ChubbsBunns** [AY2223S2-CS2113-W13-2/tp#21]
As a user who wants to keep track of their exercises, I wish to have a history of all my past exercises that I have accomplished, so that I can keep track and feel good about all the workouts I have accomplished.

- User can list out the history of all his or her accomplished workouts
- i.e. Each session should show the date and exercises done within that session

**Comment by EangJS** [comment]
Hi all, I have created the json read writers
