### ISSUE TITLE
Refactor different states into different module inputs

### ISSUE THREAD

**Issue by ChubbsBunns** [AY2223S2-CS2113-W13-2/tp#57]
Considering the addition of the start and finish exercise feature, we need to allow different commands to do different things in different states. 

- The command handler class should now manage which state to flow to depending on certain conditions (e.g. whether an exercise is ongoing or not)
- There should be more succinct command handler classes for different states that implements all the commands.

**Comment by EangJS** [comment]
Is this issue resolved? Can close?
